# Generated by Django 4.2 on 2023-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('ki', 'Kiswahili'), ('lu', 'Luo')], default='lu', help_text='Choose Book Language', max_length=2)),
            ],
            options={
                'ordering': ['language_name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='language_name',
            field=models.ManyToManyField(help_text='Select a language of the book', to='catalog.language'),
        ),
    ]
