# Generated by Django 4.2 on 2023-04-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language_name',
            field=models.ManyToManyField(blank=True, help_text='Select a language of the book', to='catalog.language'),
        ),
    ]
