# Generated by Django 4.2 on 2023-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(blank=True, default='lu', help_text='Choose Book Language', max_length=2),
        ),
    ]
